#!/usr/bin/env python3

import re
#find all occurence of the ApoI restriction site
rest_sites = []
with open ("Python_07_ApoI.fasta", "r") as fasta_read:
    for line in fasta_read:
        line = line.rstrip()
        if re.findall(r'[AG]AATT[CT]',line):
            rest_sites += re.findall(r'[AG]AATT[CT]',line)
print(rest_sites)

#print sequence with ^ at the cut site
sequence = '>seq1 GAATTCAAGTTCTTGTGCGCACACAAATCCAATAAAAACTATTGTGCACACAGACGCGAC TTCGCGGTCTCGCTTGTTCTTGTTGTATTCGTATTTTCATTTCTCGTTCTGTTTCTACTT AACAATGTGGTGATAATATAAAAAATAAAGCAATTCAAAAGTGTATGACTTAATTAATGA GCGATTTTTTTTTTGAAATCAAATTTTTGGAACATTTTTTTTAAATTCAAATTTTGGCGA AAATTCAATATCGGTTCTACTATCCATAATATAATTCATCAGGAATACATCTTCAAAGGC AAACGGTGACAACAAAATTCAGGCAATTCAGGCAAATACCGAATGACCAGCTTGGTTATC AATTCTAGAATTTGTTTTTTGGTTTTTATTTATCATTGTAAATAAGACAAACATTTGTTC CTAGTAAAGAATGTAACACCAGAAGTCACGTAAAATGGTGTCCCCATTGTTTAAACGGTT GTTGGGACCAATGGAGTTCGTGGTAACAGTACATCTTTCCCCTTGAATTTGCCATTCAAA ATTTGCGGTGGAATACCTAACAAATCCAGTGAATTTAAGAATTGCGATGGGTAATTGACA TGAATTCCAAGGTCAAATGCTAAGAGATAGTTTAATTTATGTTTGAGACAATCAATTCCC CAATTTTTCTAAGACTTCAATCAATCTCTTAGAATCCGCCTCTGGAGGTGCACTCAGCCG CACGTCGGGCTCACCAAATATGTTGGGGTTGTCGGTGAACTCGAATAGAAATTATTGTCG CCTCCATCTTCATGGCCGTGAAATCGGCTCGCTGACGGGCTTCTCGCGCTGGATTTTTTC ACTATTTTTGAATACATCATTAACGCAATATATATATATATATATTTAT'
sequence = sequence.replace(' ','').replace('>seq1','')

for site in re.finditer(r'[AG](AATT)[CT]',sequence):
    to_cut = site.group(1)
    seq_new = re.sub(to_cut,'^AATT',sequence)

#cut fragments
seq_split = seq_new.split('^')
#sort by length
seq_split = sorted(seq_split, key=len, reverse=True)
for seq in seq_split:
    print(seq)
