#!/usr/bin/env python3

#define sequences
seq1 = '------------------------------------------------------------ -------------------------AGCACCCTCCCACCTCATCCCACCCTTCTGATCTC AATCCAACGTCGCATCTCCACCGTCTCGC-----GGATCGACCCAGCGAAGTCC----CT CCCGCCCCCAAAGTCCC----------CCAAATCTTGCAGTTCCCTCCTAAATCCTCCCC ATATAAACCAACCCCCCGCCCTCAGATCCCTAATC-CCATCGCA--AGCATCAGACTCCC TCCAAAGCAGGCAGCAGCTCCTCTTCTTCCTAATCACACTATCTCGGAGAGGAGCGGCCA TGTCTGGGCGCGACAAGGGCGGCAAGGGGCTGGGCAAGGGCGGCGCCAAGCGGCACCGGA AGGTCCTCCGCGACAACATCCAGGGCATCACCAAGCCGGCGATCCGGAGGCTGGCCAGGA GGGGCGGCGTGAAGCGCATCTCCGGCCTCATCTACGAGGAGACCCGCGGCGTCCTCAAGA TCTTCCTCGAGAACGTCATCCGCGACGCCGTCACCTACACCGAGCACGCCCGCCGCAAAA CCGTCACCGCCATGGACGTCGTCTACGCGCTCAAGCGCCAGGGCCGCACCCTCTACGGCT TCGGAGGCTAGATTTGTGTGGTGAAGCAACTTCCTCGTTTGCTCTGTGATCTGTGCTGTC GTAGATGAGATTTACTGATTTGGCGTGCGCC---GGTTGTATTCTGTCATGGGGTTCAGT GGGCTGTGTAATACCTTGCTCTGTACTTCTGTTCAA----TGCAATCACTTCTATTC--- ----------------TGAA-----------------'
seq2 = 'TCTAGAGATGGCGCCATTTGATTCCAGCAGCCACAAAGCACTAGAACAATCGATGCTAAG AGGTGACAGGAAAAACAGGCTGCAAAGACCCAGACAATGGAATGCAGCGGTGGTCAGCCT AAAACACTGTAGAAGGGCAAGATGAGCTGAGTAATTTTTAACTGGGCATCATTTTTAGAA ACTGGAGTTTAAGTACCCCCTTTTCCATTTTTTCCTGAAGTCGTGGGCAGGGCGCAAGGT CTGTGAATCGGCCGACCGGATGCAGCTGGTGTGGAGAGTTCCCAATCAGGTCCGATTTAT TACTATATAAAGTACTGCTGC--GAGGCTTGCCGTGTTGCATTTTGTTTAGTACAAGACA TGTCTGGGCGCGGCAAAGGCGGGAAGGGTCTGGGCAAAGGAGGCGCTAAGCGCCACCGCA AAGTTCTGCGCGACAACATTCAGGGCATCACCAAGCCCGCCATCCGACGCCTGGCACGGC GTGGAGGCGTTAAGCGCATCTCAGGCCTTATATACGAGGAGACACGCGGAGTTCTTAAAG TGTTTTTGGAGAATGTAATCCGCGATGCAGTTACCTACACGGAGCACGCCAAACGCAAGA CAGTCACAGCCATGGACGTGGTTTACGCGCTCAAGCGCCAGGGCCGCACCCTGTATGGCT TTGGCGGCTGAGTGTTTTACTTACTTACACGGTTCCTCAAAGGCCCTTCTCAGGGCCACC CATGAAGTCTGTGAAAGAGCTGTAGACTAAAGATAGTTAATTTCTTAAGAAC-----ACT TAAACGTATGGCAGTTTTGGCAAATTAGCGATTCCACATAAGCAGTCGCTGAAGTTTGAG GTTCGGTGCCCCTTTCAGCATTACTTAGTGGTTAAAA'
#remove spaces
seq1 = seq1.replace(' ','')
seq2 = seq2.replace(' ','')
print(seq1)
sum_same = 0
sum_diff = 0
for i in range(len(seq1)):
    if seq1[i] == '-' or seq2[i] == '-':
        continue
    elif seq1[i] == seq2[i]:
        sum_same = sum_same + 1
    else:
        sum_diff = sum_diff + 1
print(f"percent same is {(sum_same/(sum_same+sum_diff)):.2%}")
